-- This folder holds incremental schema migrations.
-- The initial schema is defined in docs/knowledge/schema/base-schema.sql.
-- New migrations are added as: YYYYMMDD_NNN_description.sql
-- See docs/knowledge/schema/migrations-guide.md for instructions.
